// import type { Metadata } from "next";
// import { Mona_Sans, Geist } from "next/font/google";
// import "./globals.css";
// import { cn } from "@/lib/utils";

// const geist = Geist({subsets:['latin'],variable:'--font-sans'});

// const monaSans = Mona_Sans({
//   variable: "--font-mona-sans",
//   subsets: ["latin"],
// });


// export const metadata: Metadata = {
//   title: "PrepEdge",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en" className={cn("dark", "font-sans", geist.variable)}>
//       <body className={`${monaSans.className} antialiased`}>{children}</body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Mona_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner"; // Toaster yahan global rakhein

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });
const monaSans = Mona_Sans({ variable: "--font-mona-sans", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PrepEdge",
  description: "AI Interview Practice Platform",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn("dark", "font-sans", geist.variable)}>
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
      </head>
      <body className={`${monaSans.className} bg-black text-white antialiased`}>
        {children}
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}


